CREATE TABLE KHACHHANG
(
	MAKH char(4) NOT NULL,
	HOTEN varchar(40),
	DCHI varchar(50),
	SODT varchar(20),
	NGSINH smalldatetime,
	NGDK smalldatetime,
	DOANHSO money,
	CONSTRAINT PK_MAKH PRIMARY KEY (MAKH)
)

ALTER TABLE KHACHHANG
ADD CHECK (NGDK > NGSINH)

CREATE TABLE NHANVIEN
( 
	MANV char(4) NOT NULL,
	HOTEN varchar (40),
	SODT varchar (20),
	NGVL smalldatetime,
	CONSTRAINT PK_MANV PRIMARY KEY (MANV)
)

CREATE TABLE SANPHAM
(
	MASP char(4) NOT NULL,
	TENSP varchar(40),
	DVT varchar(20),
	NUOCSX varchar (40),
	GIA money,
	CONSTRAINT PK_MASP PRIMARY KEY (MASP)
)

CREATE TABLE HOADON 
( 
	SOHD int NOT NULL,
	NGHD smalldatetime,
	MAKH char(4),
	MANV char(4),
	TRIGIA money,
	CONSTRAINT PK_SOHD PRIMARY KEY (SOHD),
	CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_MANV FOREIGN KEY (MANV) REFERENCES  NHANVIEN(MANV),
)

CREATE TABLE CTHD
(
	SOHD int NOT NULL,
	MASP char(4) NOT NULL,
	SL int,
	CONSTRAINT PK_CTHD PRIMARY KEY (SOHD,MASP),
	CONSTRAINT FK_SOHD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
	CONSTRAINT FK_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
)

ALTER TABLE SANPHAM
ADD GHICHU varchar(20)

ALTER TABLE KHACHHANG
ADD LOAIKH tinyint

ALTER TABLE SANPHAM 
ALTER COLUMN GHICHU varchar(100)

ALTER TABLE SANPHAM
DROP COLUMN GHICHU

ALTER TABLE KHACHHANG 
ALTER COLUMN LOAIKH varchar(50)

ALTER TABLE SANPHAM
ADD CONSTRAINT CK_DVT CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'));

ALTER TABLE SANPHAM
ADD CHECK (GIA > 500)

ALTER TABLE CTHD
ADD CHECK (SL > 0)

